# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Simple Pipe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      myValues:
        description: 'Input Values'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: greetings-jar
        path: build/libs
  
  test-run:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: greetings-jar
    - shell: bash
      run: 
        java -jar greetings-actions.jar ${{ github.event.inputs.myValues }}
        
  count-args:
    runs-on: ubuntu-latest
    
    steps:
      - id: report-count
        uses: mkolakow/arg-count-action@main
        with:
          arguments-to-count: ${{ github.event.inputs.myValues }}
      - run: |
          echo 'Yo dawg: ${{ secrets.WORKFLOW_USE }}'
      - shell: bash
        run: |
          echo argument count is ${{ steps.report-count.outputs.arg-count }}
        
  create-issue-on-failure:
    runs-on: ubuntu-latest
    needs: [test-run, count-args]
    if: always() && failure()
    steps:
      - name: invoke workflow to create issue
        run: >
          curl -X POST
          -H "authorization: Bearer ${{ secrets.WORKFLOW_USE }}"
          -H "Accept: application/vnd.github.v3+json"
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-failure-issue.yml/dispatches"
          -d '{"ref":"main",
               "inputs":
               {"title":"Automated workflow failure issue for commit ${{ github.sha }}",
                "body":"This issue was automatically created by the GitHub Action workflow ** ${{ github.workflow }} **"}
              }'
               
    
